"""Markdown reporting (PRD 13).

The report is the deliverable, so its structure carries the product's central
claim: raw facts, interpretations, and confirmed findings are three different
things and are never mixed. A beginner reading this must not be able to mistake
"no CSP header" for "this site is vulnerable to XSS".
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from .. import __version__
from .db import Database
from .models import Engagement
from .teaching import TeachingLibrary

SEVERITY_ORDER = {"high": 0, "medium": 1, "low": 2, "info": 3}

HOW_TO_READ = """\
This report separates three different kinds of statement, and the difference matters:

| Kind | What it means | How much you can rely on it |
|---|---|---|
| **Observation** | A raw fact that was collected, with its source and timestamp. | High - it is what the source returned. |
| **Hint / interpretation** | A reading of one or more observations, with confidence and limitations. | It is a hypothesis. Verify before acting on it. |
| **Confirmed finding** | Something a human has verified by hand. | None appear here automatically. |

Recon Helper Pro does not confirm vulnerabilities. Every entry in the Findings
section below is an interpretation. A missing security header is not a
vulnerability; it is a hardening gap whose importance depends on what the
application does. Severity hints are context-aware suggestions, never scores.
"""


@dataclass(slots=True)
class Report:
    engagement: Engagement
    markdown: str
    path: Path | None = None


def _escape_cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


class ReportBuilder:
    """Builds one engagement's Markdown report from stored data."""

    def __init__(self, db: Database, teaching: TeachingLibrary) -> None:
        self.db = db
        self.teaching = teaching

    def build(self, engagement: Engagement) -> str:
        assert engagement.id is not None
        engagement_id = engagement.id
        runs = list(reversed(self.db.list_runs(engagement_id, limit=1000)))
        observations = self.db.observations_for_engagement(engagement_id)
        findings = self.db.findings_for_engagement(engagement_id)
        assets = self.db.list_assets(engagement_id)
        scope_entries = self.db.list_scope_entries(engagement_id)
        activity = self.db.list_activity(engagement_id, limit=1000)

        parts: list[str] = []
        parts.append(self._header(engagement, runs, observations))
        parts.append(self._scope(scope_entries))
        parts.append(self._versions(runs, observations))
        parts.append(self._coverage(runs))
        parts.append(self._contact_accounting(activity))
        parts.append(self._assets(assets))
        parts.append("## How to read this report\n\n" + HOW_TO_READ)
        parts.append(self._findings(findings))
        parts.append(self._observations(observations))
        parts.append(self._glossary(observations, findings))
        parts.append(
            "---\n\n*Generated by Recon Helper Pro "
            f"{__version__}. Only run against systems you are authorized to test.*\n"
        )
        return "\n\n".join(part for part in parts if part.strip())

    # -- sections ---------------------------------------------------------
    def _header(
        self, engagement: Engagement, runs: list[Any], observations: list[dict[str, Any]]
    ) -> str:
        times = [str(item["collected_at"]) for item in observations if item.get("collected_at")]
        period = (
            f"{min(times)} to {max(times)}" if times else "no data collected yet"
        )
        modes = sorted({run.mode.value for run in runs})
        return (
            f"# Recon report - {engagement.name}\n\n"
            f"*Generated {datetime.now(timezone.utc).isoformat(timespec='seconds')}*\n\n"
            f"**Engagement:** {engagement.name}  \n"
            f"**Created:** {engagement.created_at}  \n"
            f"**Collection period:** {period}  \n"
            f"**Description:** {engagement.description or '(none given)'}\n\n"
            "## Methodology\n\n"
            "Recon Helper Pro collected this data using bundled modules of three kinds:\n\n"
            "- `third-party` - obtained from resolvers and public data providers; the target "
            "was not contacted.\n"
            "- `direct-read` - a small number of read-only requests to the target.\n"
            "- `enumerative` - several requests to check a fixed list of well-known published "
            "files.\n\n"
            f"Modes used in this engagement: {', '.join(modes) if modes else 'none yet'}. "
            "No exploitation, brute force, fuzzing or intrusive scanning was performed - those "
            "are outside what this tool does. Every destination was checked against the scope "
            "below before contact, re-checked after DNS resolution, and re-checked on every "
            "redirect."
        )

    def _scope(self, entries: Iterable[Any]) -> str:
        lines = ["## Scope and exclusions", ""]
        entries = list(entries)
        if entries:
            lines += ["| Type | Entry |", "|---|---|"]
            lines += [f"| {entry.type.value} | `{entry.display()}` |" for entry in entries]
        else:
            lines.append("*No scope entries were recorded for this engagement.*")
        lines += [
            "",
            "**Exclusions.** A bare hostname authorizes that host only - subdomains, IP "
            "addresses and ranges are in scope only where listed above. Regardless of scope, "
            "the entire link-local range (`169.254.0.0/16`, `fe80::/10`) and known cloud "
            "metadata endpoints are hard-blocked and were never contacted.",
        ]
        return "\n".join(lines)

    def _versions(self, runs: list[Any], observations: list[dict[str, Any]]) -> str:
        module_versions = sorted({(run.module, run.module_version) for run in runs})
        providers = sorted({str(item.get("source_provider", "")) for item in observations if item.get("source_provider")})
        lines = [
            "## Versions and sources",
            "",
            f"- **Recon Helper Pro:** {__version__}",
            "- **Modules used:** "
            + (", ".join(f"{name} {version}" for name, version in module_versions) or "none"),
            "- **Data providers:** " + (", ".join(providers) or "none"),
        ]
        return "\n".join(lines)

    def _coverage(self, runs: list[Any]) -> str:
        lines = ["## Coverage", ""]
        if not runs:
            lines.append("*No modules have been run yet.*")
            return "\n".join(lines)
        lines += [
            "| Module | Mode | Target | Status | Requests | Started | Notes |",
            "|---|---|---|---|---|---|---|",
        ]
        for run in runs:
            lines.append(
                "| {module} | {mode} | {target} | **{status}** | {requests} | {started} | {note} |".format(
                    module=_escape_cell(run.module),
                    mode=_escape_cell(run.mode.value),
                    target=_escape_cell(run.target),
                    status=_escape_cell(run.status.value),
                    requests=run.request_count,
                    started=_escape_cell(run.started_at),
                    note=_escape_cell(run.error_summary or ""),
                )
            )
        statuses = {}
        for run in runs:
            statuses[run.status.value] = statuses.get(run.status.value, 0) + 1
        lines += [
            "",
            "Summary: "
            + ", ".join(f"{count} {status}" for status, count in sorted(statuses.items()))
            + ". A `partial` or `failed` module does not invalidate the rest of the run; it "
            "means that specific check did not complete, and the gap is recorded here rather "
            "than hidden.",
        ]
        return "\n".join(lines)

    def _contact_accounting(self, activity: list[dict[str, Any]]) -> str:
        contacting = [
            event for event in activity if event.get("mode") in ("direct-read", "enumerative")
        ]
        lines = ["## Direct-contact accounting", ""]
        if not contacting:
            lines.append(
                "No request was sent to the target: every module used in this engagement "
                "obtained its data from third parties."
            )
            return "\n".join(lines)
        total = sum(int(event.get("request_count") or 0) for event in contacting)
        lines += [
            f"{total} request(s) were sent directly to targets in this engagement.",
            "",
            "| When | Module | Mode | Host | Requests | Outcome | Override |",
            "|---|---|---|---|---|---|---|",
        ]
        for event in contacting:
            lines.append(
                "| {when} | {module} | {mode} | {host} | {count} | {outcome} | {override} |".format(
                    when=_escape_cell(event.get("timestamp")),
                    module=_escape_cell(event.get("module")),
                    mode=_escape_cell(event.get("mode")),
                    host=_escape_cell(event.get("target")),
                    count=int(event.get("request_count") or 0),
                    outcome=_escape_cell(event.get("outcome")),
                    override=_escape_cell(event.get("override_reason") or "-"),
                )
            )
        overrides = [event for event in contacting if event.get("override_reason")]
        if overrides:
            lines += [
                "",
                f"**{len(overrides)} out-of-scope override(s) were confirmed by the operator.** "
                "Each is listed above with its reason.",
            ]
        return "\n".join(lines)

    def _assets(self, assets: list[Any]) -> str:
        lines = ["## Assets", ""]
        if not assets:
            lines.append("*No assets recorded.*")
            return "\n".join(lines)
        lines += [
            "Assets discovered by a module are **recorded only**. Nothing here was contacted "
            "because it was discovered; only assets covered by the scope above were eligible "
            "for contact at all.",
            "",
            "| Kind | Value | In scope | Discovered by | First seen |",
            "|---|---|---|---|---|",
        ]
        for asset in assets:
            lines.append(
                "| {kind} | `{value}` | {scope} | {by} | {seen} |".format(
                    kind=asset.kind.value,
                    value=_escape_cell(asset.value),
                    scope="yes" if asset.in_scope else "no",
                    by=_escape_cell(asset.discovered_by),
                    seen=_escape_cell(asset.first_seen),
                )
            )
        return "\n".join(lines)

    def _findings(self, findings: list[dict[str, Any]]) -> str:
        lines = ["## Findings (interpretations, not confirmed vulnerabilities)", ""]
        if not findings:
            lines.append("*No interpretations were produced.*")
            return "\n".join(lines)
        ordered = sorted(
            findings,
            key=lambda item: (
                SEVERITY_ORDER.get(str(item.get("severity_hint")), 9),
                str(item.get("title")),
            ),
        )
        for index, finding in enumerate(ordered, start=1):
            supporting = json.loads(str(finding.get("supporting_observation_ids") or "[]"))
            lines += [
                f"### {index}. {finding.get('title')}",
                "",
                f"- **Category:** {finding.get('category')}",
                f"- **Asset:** `{finding.get('asset_value') or 'n/a'}`",
                f"- **Severity hint:** {finding.get('severity_hint')} "
                "(context-aware suggestion, not a score)",
                f"- **Confidence:** {finding.get('confidence')}",
                f"- **Recorded:** {finding.get('created_at')}",
                "",
                "**Interpretation.** " + str(finding.get("interpretation_text", "")),
                "",
                "**Limitations.** " + str(finding.get("limitations") or "None stated."),
                "",
                "**Supporting observations.** "
                + (", ".join(f"`{key}`" for key in supporting) if supporting else "none recorded"),
                "",
            ]
        return "\n".join(lines)

    def _observations(self, observations: list[dict[str, Any]]) -> str:
        lines = ["## Observations (raw facts)", ""]
        if not observations:
            lines.append("*No observations recorded.*")
            return "\n".join(lines)
        grouped: dict[str, list[dict[str, Any]]] = {}
        for observation in observations:
            grouped.setdefault(str(observation.get("type")), []).append(observation)
        for obs_type in sorted(grouped):
            lines += [
                f"### `{obs_type}`",
                "",
                "| Asset | Value | Source | Collected | Confidence | Module |",
                "|---|---|---|---|---|---|",
            ]
            for observation in grouped[obs_type]:
                lines.append(
                    "| `{asset}` | {value} | {source} | {when} | {confidence} | {module} {version} |".format(
                        asset=_escape_cell(observation.get("asset_value") or "-"),
                        value=_escape_cell(observation.get("normalized_value")),
                        source=_escape_cell(observation.get("source_provider")),
                        when=_escape_cell(observation.get("collected_at")),
                        confidence=_escape_cell(observation.get("confidence")),
                        module=_escape_cell(observation.get("module")),
                        version=_escape_cell(observation.get("module_version")),
                    )
                )
            lines.append("")
        return "\n".join(lines)

    def _glossary(
        self, observations: list[dict[str, Any]], findings: list[dict[str, Any]]
    ) -> str:
        haystack = " ".join(
            [str(item.get("type", "")) for item in observations]
            + [str(item.get("category", "")) for item in findings]
            + [str(item.get("title", "")) for item in findings]
        ).lower()
        entries = self.teaching.glossary()
        used = {term: body for term, body in entries.items() if term.split()[0] in haystack}
        if not used:
            used = dict(list(entries.items())[:6])
        lines = ["## Glossary", ""]
        for term, body in sorted(used.items()):
            first_line = body.strip().splitlines()[0] if body.strip() else ""
            lines.append(f"- **{term}** - {first_line}")
        return "\n".join(lines)


def write_report(
    db: Database,
    teaching: TeachingLibrary,
    engagement: Engagement,
    exports_dir: Path,
) -> Report:
    """Render the report and write it to ``exports/`` with a timestamped name."""
    builder = ReportBuilder(db, teaching)
    markdown = builder.build(engagement)
    exports_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    safe_name = "".join(
        character if character.isalnum() or character in "-_" else "-"
        for character in engagement.name
    ).strip("-") or f"engagement-{engagement.id}"
    path = exports_dir / f"{safe_name}-{stamp}.md"
    path.write_text(markdown, encoding="utf-8")
    return Report(engagement=engagement, markdown=markdown, path=path)
